name: Conventional Commits

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webiny/action-conventional-commits@v1.1.0
